<?php

namespace App\Constants;

return [
    //Home
    'SLIDER_IMAGE_MAX_SIZE'=>'2048',
    'SLIDER_IMAGE_MIN_SIZE'=>'180',

    'COURSES_OFFERED_IMAGE_MAX_SIZE'=>'150',
    'COURSES_OFFERED_IMAGE_MIN_SIZE'=>'10',

    'TESTIMONIAL_IMAGE_MAX_SIZE'=>'150',
    'TESTIMONIAL_IMAGE_MIN_SIZE'=>'10',
];